[workspace]
members = [
  "./contracts/diesel_amm_contract",
  "./contracts/diesel_validation_hook",
  "./contracts/diesel_amm_proxy",
  
  "./contracts/mocks/mock_token",
  "./libraries/interfaces",
  "./libraries/utils",
  "./libraries/math",

]
